[package]
name = "core-space"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
anyhow.workspace = true
clap.workspace = true
toml_edit.workspace = true
git2.workspace = true
url.workspace = true
dirs-next.workspace = true
crates-index.workspace = true
reqwest.workspace = true
semver.workspace = true
rustc-hash.workspace = true
indexmap.workspace = true
cargo_metadata.workspace = true
